Default:
  MQ_SERVER_IP: '192.168.1.109'
  FILE_SERVER_IP: '192.168.1.109'
  HIDDEN_PATH: '/data1/work/html/outFile'
  MINIO_ACCESS_KEY: 'adminminio'
  MINIO_SECRET_KEY: 'adminminio'
  MINIO_SERVER_IP: '192.168.1.109'
  MINIO_PORT: 9000
